# -*- coding: utf-8 -*-
"""MD5Hashalgo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pvbNI_uW41OwpSxZXz4fLBfj4-FimLho
"""

import hashlib

#using hexdigest
print(hashlib.md5("This is a string".encode('utf-8')).hexdigest())
 
 
#using digest
print(hashlib.md5("This is a string".encode('utf-8')).digest())