# -*- coding: utf-8 -*-
"""SHA1Hashalgo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pvbNI_uW41OwpSxZXz4fLBfj4-FimLho
"""

import hashlib

hash_object = hashlib.sha1(b'Hello World')
hex_dig = hash_object.hexdigest()
print(hex_dig)